import { redirect } from "next/navigation";
import { createGame } from "@/app/game-actions";
import { createClient } from "@/lib/supabase/server";

export default async function CreatePage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams;
  const error = typeof params.error === "string" ? params.error : null;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login?next=/create");
  const { data: activities } = await supabase.from("activities").select("id,code,name_en,play_mode").eq("active", true).order("name_en");
  return <div className="page"><p className="eyebrow">Create</p><h1>Who are you missing?</h1><p className="lead">Create the game first. Find the missing person next.</p>{error && <p className="notice error">{error}</p>}<form action={createGame} className="wizard"><label>What are you playing?<select name="activity_id" required>{activities?.map(a => <option key={a.id} value={a.id}>{a.name_en}</option>)}</select></label><label>Mode<select name="mode" defaultValue="physical"><option value="physical">Physical</option><option value="online">Online</option></select></label><div className="two-col"><label>Date<input name="date" type="date" required /></label><label>Start<input name="start_time" type="time" required /></label></div><label>End time<input name="end_time" type="time" required /></label><label>Physical location<input name="location" placeholder="MyFitness Sāga, Rīga" /></label><label>City<input name="city" placeholder="Rīga" /></label><label>Online platform<input name="online_platform" placeholder="Chess.com, Lichess, other" /></label><label>How many people are missing?<input name="players_needed" type="number" min="1" defaultValue="1" required /></label><label>Skill level<select name="skill" defaultValue="any"><option value="any">Any level</option><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label><label>Gender preference<select name="gender_preference" defaultValue="anyone"><option value="anyone">Anyone</option><option value="men">Men</option><option value="women">Women</option><option value="mixed">Mixed</option></select></label><label>Payment<select name="payment_method" defaultValue="free"><option value="free">Free</option><option value="pay_at_venue">Pay at venue</option><option value="pay_in_advance">Pay in advance</option></select></label><label>Total cost (€)<input name="total_cost" type="number" min="0" step="0.01" defaultValue="0" /></label><label>Venue booked?<select name="venue_booked" defaultValue="false"><option value="false">Not booked yet</option><option value="true">Booked</option></select></label><label>Free cancellation until<select name="cancellation_policy_minutes" defaultValue="180"><option value="0">Anytime</option><option value="60">1 hour before</option><option value="180">3 hours before</option><option value="360">6 hours before</option><option value="720">12 hours before</option><option value="1440">24 hours before</option></select></label><label>Visibility<select name="visibility" defaultValue="public"><option value="public">Public</option><option value="private">Private link</option></select></label><label>Notes<textarea name="description" rows={4} placeholder="Anything players should know?" /></label><button type="submit" className="button primary wide">Publish game</button></form></div>;
}
